# Generated by Django 4.0.4 on 2022-04-30 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('established_year', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('production_year', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expiration', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('made_in', models.CharField(max_length=50)),
                ('cloth_type', models.CharField(choices=[('Cotton', 'نخ پنبه'), ('Plastic', 'پلاستیک'), ('Tetron', 'تترون'), ('Lee', 'لی'), ('Raven', 'ریون'), ('Velvet', 'مخمل')], max_length=10, null=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'large'), ('Xl', 'XLarge'), ('2xL', '2XLarge'), ('3xL', '3XLarge'), ('4xL', '4XLarge'), ('5xL', '5XLarge')], max_length=3, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shampoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('production_year', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expiration', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('made_in', models.CharField(max_length=50)),
                ('shampoo_type', models.CharField(choices=[('dry', 'dry hair'), ('oily', 'oily hair'), ('normal', 'normal hair'), ('childish', 'childish'), ('conditioner', 'conditioner')], max_length=20, null=True)),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('production_year', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expiration', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('made_in', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('package_weight', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
