# Generated by Django 4.0.4 on 2022-04-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='production_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shampoo',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shampoo',
            name='production_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='production_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='shampoo',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
